// ===== NaoCraft Backend — Utility Helpers =====

import { randomBytes } from 'crypto';
import { readdir, stat } from 'fs/promises';
import { join } from 'path';
import type { FileInfo } from '../types';

/** Generate a short unique ID */
export function generateId(): string {
  return randomBytes(6).toString('hex');
}

/** Get the base servers directory */
export function getServersDir(): string {
  return join(process.cwd(), '..', 'servers');
}

/** Parse server.properties file content into key-value object */
export function parseServerProperties(content: string): Record<string, string> {
  const props: Record<string, string> = {};
  const lines = content.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const eqIndex = trimmed.indexOf('=');
      if (eqIndex !== -1) {
        const key = trimmed.substring(0, eqIndex).trim();
        const value = trimmed.substring(eqIndex + 1).trim();
        props[key] = value;
      }
    }
  }
  return props;
}

/** Serialize key-value object back to server.properties format */
export function serializeServerProperties(props: Record<string, string>): string {
  const header = `#Minecraft server properties\n#Generated by NaoCraft\n`;
  const lines = Object.entries(props)
    .map(([key, value]) => `${key}=${value}`)
    .sort()
    .join('\n');
  return header + lines + '\n';
}

/** List files/directories in a given path */
export async function listDirectory(dirPath: string): Promise<FileInfo[]> {
  const entries = await readdir(dirPath, { withFileTypes: true });
  const results: FileInfo[] = [];

  for (const entry of entries) {
    const fullPath = join(dirPath, entry.name);
    try {
      const stats = await stat(fullPath);
      results.push({
        name: entry.name,
        path: fullPath,
        isDirectory: entry.isDirectory(),
        size: stats.size,
        modifiedAt: stats.mtime.toISOString(),
      });
    } catch {
      // Skip files we can't stat
    }
  }

  return results.sort((a, b) => {
    // Directories first, then alphabetical
    if (a.isDirectory && !b.isDirectory) return -1;
    if (!a.isDirectory && b.isDirectory) return 1;
    return a.name.localeCompare(b.name);
  });
}

/** Format bytes to human-readable string */
export function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

/** Sleep helper */
export function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}
